# fly.toml app configuration file generated for deno-books on 2025-01-03T13:14:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'deno-books'
primary_region = 'lhr'

[build]

[env]
  PORT = '8080'

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"

[processes]
  app = 'run -A ./server.ts'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
